"""Documentation and Containerfile generation from compose.yaml metadata.
"""

from __future__ import annotations

import argparse
import os
from datetime import date
from pathlib import Path
from typing import Any

from .config import _confident_prefix

try:
    import jinja2
except ImportError:
    jinja2 = None

import dataclasses

import dbuild
from dbuild import log
from dbuild.config import (
    DEFAULT_COMMUNITY,
    AppTestConfig,
    Config,
    DeprecationInfo,
    Metadata,
    Variant,
)

# Constants for placeholder generation
CONFIG_ROOT_VAR = "@CONTAINER_CONFIG_ROOT@"
SHARED_PATHS = ["/downloads", "/movies", "/tv", "/music", "/books", "/media"]

HEADER_TEMPLATE = """# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: {source}
# --------------------------------------------------------------------------

"""

README_HEADER = """<!--
THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
Source: dbuild templates
-->

"""


# ── Documentation helpers ─────────────────────────────────────────────

def _fields_for_docs(cls) -> list[tuple[str, str, str]]:
    """Extract (field, display_default, description) from a dataclass.

    Only fields with a ``desc`` key in their metadata are included,
    allowing internal fields to be silently skipped.
    """
    result = []
    for f in dataclasses.fields(cls):
        desc = f.metadata.get("desc", "")
        if not desc:
            continue
        if "display_default" in f.metadata:
            default = f.metadata["display_default"]
        elif f.default is not dataclasses.MISSING:
            val = f.default
            if val is None:
                default = "None"
            elif isinstance(val, bool):
                default = str(val).lower()
            elif isinstance(val, str):
                default = f'"{val}"' if val else '""'
            else:
                default = str(val)
        else:
            default = "(required)"
        result.append((f.name, default, desc))
    return result


# ── Extended Documentation Content ────────────────────────────────────

def _global_config_doc_path() -> str:
    """Return the global config path for display in generated docs.

    Unlike dbuild.config._global_config_path(), this does NOT fall back to
    sys.prefix. During an isolated PEP 517 build that doesn't export
    PREFIX (e.g. a port build), sys.prefix resolves to pip/build's
    throwaway virtualenv, not any real install location -- showing that
    path would be actively wrong, not just imprecise. When the prefix
    can't be determined confidently, show the literal placeholder instead.
    """
    prefix_path = _confident_prefix()
    if prefix_path is None:
        return "$PREFIX/etc/daemonless.yaml"
    return str(prefix_path / "etc" / "daemonless.yaml")


DOCS_CONTENT = {
    "DESCRIPTION": (
        "dbuild provides a streamlined interface for creating and managing OCI-compliant "
        "containers that run natively in FreeBSD Jails. It eliminates the friction of "
        "configuring ocijail, networking, and jail templates by using a 'Registry-First' "
        "approach. Configuration is automatically derived from Git remotes and standard "
        "Compose files, allowing for reproducible builds across local and CI environments."
    ),
    "ENVIRONMENT": {
        "DBUILD_REGISTRY": "Override the target container registry (e.g., ghcr.io/myorg).",
        "GITHUB_TOKEN": "Authentication token for GitHub Packages and build secrets.",
        "GITHUB_ACTOR": "The username associated with GITHUB_TOKEN.",
        "DOCKERHUB_USERNAME": "Enable mirroring by providing a Docker Hub username.",
        "DOCKERHUB_TOKEN": "Personal access token for Docker Hub mirroring.",
        "CHROME_BIN": "Path to the Chrome/Chromium binary for screenshot testing.",
    },
    "FILES": {
        "compose.yaml": "The primary source of truth for metadata and documentation.",
        ".daemonless/config.yaml": "Project-specific build and test overrides.",
    },
    "GLOBAL_CONFIGURATION_EXAMPLE": """pkg_cache_url: pkg-cache.example.lan:8080""",
    "EXAMPLES": [
        ("Build and push all variants", "dbuild build --push"),
        ("Initialize from a FreeBSD Port", "dbuild init --freebsd-port net-p2p/transmission"),
        ("Run specific tests", "dbuild test --variant pkg"),
    ],
    "EXIT_STATUS": {
        "0": "Success.",
        "1": "Build, test, or system failure.",
        "2": "Command-line usage error (invalid flags or arguments).",
    },
    "METADATA_FIELDS": _fields_for_docs(Metadata),
    "BUILD_FIELDS": [
        # No BuildConfig dataclass yet — these are parsed from a raw dict in load().
        ("pkg_name",      "None",        "Default FreeBSD package name (auto-injected as --build-arg PKG_NAME and used for version extraction across variants)"),
        ("architectures", '["amd64"]',   'List of architectures to build (e.g. `["amd64", "arm64"]`)'),
    ],
    "VARIANT_FIELDS":     _fields_for_docs(Variant),
    "CIT_FIELDS":         _fields_for_docs(AppTestConfig),
    "DEPRECATION_FIELDS": _fields_for_docs(DeprecationInfo),
}


def generate_manpage(parser: argparse.ArgumentParser) -> str:
    """Generate a ROFF format man page from the CLI parser."""
    today = date.today().strftime("%Y-%m-%d")
    output = []
    output.append(f'.TH DBUILD 1 "{today}" "dbuild {dbuild.VERSION}" "User Commands"')
    output.append(".SH NAME")
    output.append("dbuild \\- FreeBSD OCI container image build tool")
    output.append(".SH SYNOPSIS")
    output.append(".B dbuild")
    output.append("[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR...]")

    output.append(".SH DESCRIPTION")
    output.append(DOCS_CONTENT["DESCRIPTION"])

    subparser_actions = [
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    ]
    for subparser_action in subparser_actions:
        output.append(".SH COMMANDS")
        for choice, subparser in sorted(subparser_action.choices.items()):
            if choice == "docs":
                continue
            output.append(".TP")
            output.append(f"\\fB{choice}\\fR")
            desc = subparser.description or subparser.help
            output.append(desc)

            unique_actions = []
            seen = set()
            for action in subparser._option_string_actions.values():
                if action not in seen:
                    unique_actions.append(action)
                    seen.add(action)

            if unique_actions:
                output.append(".RS")
                for action in unique_actions:
                    opts = ", ".join(f"\\fB{o}\\fR" for o in action.option_strings)
                    help_text = (action.help or "").replace("%(default)s", str(action.default))
                    output.append(".TP")
                    output.append(opts)
                    output.append(help_text)
                output.append(".RE")

    output.append(".SH ENVIRONMENT")
    for var, desc in DOCS_CONTENT["ENVIRONMENT"].items():
        output.append(".TP")
        output.append(f"\\fI{var}\\fR")
        output.append(desc)

    output.append(".SH FILES")
    for file, desc in DOCS_CONTENT["FILES"].items():
        output.append(".TP")
        output.append(f"\\fI{file}\\fR")
        output.append(desc)

    global_config_path = _global_config_doc_path()
    output.append(".TP")
    output.append(f"\\fI{global_config_path}\\fR")
    output.append(
        "Optional host-local defaults, including pkg_cache_url for local pkg-cache injection."
    )

    output.append(".SH GLOBAL CONFIGURATION")
    output.append(
        f"The \\fI{global_config_path}\\fR file is an optional host-local "
        "config file for settings that apply on this builder, not in every "
        "image repo. To use a local pkg cache, set \\fIpkg_cache_url\\fR. "
        "dbuild injects that value into builds as \\fIPKG_CACHE_URL\\fR, "
        "and opt-in Containerfiles can use it to point FreeBSD pkg at the "
        "local cache during build. If the file or key is missing, nothing "
        "is injected."
    )
    output.append(".PP")
    output.append(f"Example \\fI{global_config_path}\\fR:")
    output.append(".IP")
    output.append(".nf")
    output.append(DOCS_CONTENT["GLOBAL_CONFIGURATION_EXAMPLE"])
    output.append(".fi")

    output.append(".SH EXAMPLES")
    for title, cmd in DOCS_CONTENT["EXAMPLES"]:
        output.append(f"{title}:")
        output.append(".IP")
        output.append(f"dbuild {cmd.replace('dbuild ', '')}")

    output.append(".SH EXIT STATUS")
    for code, desc in DOCS_CONTENT["EXIT_STATUS"].items():
        output.append(".TP")
        output.append(f"\\fB{code}\\fR")
        output.append(desc)

    output.append(".SH SEE ALSO")
    output.append(".UR https://daemonless.io/guides/dbuild/")
    output.append("Full web documentation")
    output.append(".UE")

    return "\n".join(output)


def _get_jinja_env(base: Path) -> jinja2.Environment | None:
    """Create Jinja2 environment with override priority:
    1. repo root (README.j2 alongside Containerfile.j2)
    2. .daemonless/templates/
    3. bundled dbuild templates
    """
    if jinja2 is None:
        return None

    search_paths = [
        base,
        base / ".daemonless" / "templates",
        Path(__file__).parent / "templates",
    ]
    # Filter to existing directories
    loaders = [jinja2.FileSystemLoader(str(p)) for p in search_paths if p.is_dir()]
    if not loaders:
        return None

    return jinja2.Environment(loader=jinja2.ChoiceLoader(loaders))


_SCREENSHOT_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".svg", ".mp4", ".webm"}


def _collect_screenshots(base: Path) -> list[str]:
    """Return sorted relative paths for files in .daemonless/screenshots/."""
    shots_dir = base / ".daemonless" / "screenshots"
    if not shots_dir.is_dir():
        return []
    return sorted(
        str(p.relative_to(base))
        for p in shots_dir.iterdir()
        if p.is_file() and p.suffix.lower() in _SCREENSHOT_EXTS
    )


def _normalize_base_version(raw: str, default: str = "15.1") -> str:
    """Turn a BASE_VERSION arg (which may be a pkg tag) into a FreeBSD release:
    '15-pkg' -> '15', '15.1-latest' -> '15.1', '15.1-pkg-latest' -> '15.1',
    bare 'latest'/'' -> default. Suffix order matters (-pkg-latest first)."""
    v = raw.strip().strip('"\'')
    for suffix in ("-pkg-latest", "-pkg", "-latest"):
        if v.endswith(suffix):
            v = v[: -len(suffix)]
            break
    return v if v and v != "latest" else default


def _enrich_metadata(cfg: Config, community_override: str | None = None) -> dict[str, Any]:
    """Build a context dict for templates with enriched env/vol/port data from Config."""
    meta = cfg.metadata
    docs = meta.docs if isinstance(meta.docs, dict) else {}

    # Extract jail allow.* parameters from annotations
    annotations = cfg.test.annotations if cfg.test else []
    jail_allow = [
        a.split("=")[0].replace("org.freebsd.jail.", "")
        for a in annotations
        if "org.freebsd.jail.allow." in a and "=true" in a.lower()
    ]
    mlock = "allow.mlock" in jail_allow
    sysvipc = "allow.sysvipc" in jail_allow

    # Check for AppJail support
    # meta.appjail is None = disabled, {} = bare/default, {...} = custom config
    appjail_meta = meta.appjail if hasattr(meta, "appjail") else None
    appjail_enabled = appjail_meta is not None or any(
        "io.daemonless.appjail" in a for a in annotations
    )

    # Check for Bastille OCI support (enabled by default; None = bastille: false)
    bastille_meta = meta.bastille if hasattr(meta, "bastille") else {}
    bastille_enabled = bastille_meta is not None

    # Community: Use CLI override, metadata if set (Format: Name:URL), or default to Daemonless Discord.
    community_name = ""
    community_url = ""
    community_raw = community_override or meta.community
    if not community_raw and "daemonless" in cfg.registry.lower():
        community_raw = DEFAULT_COMMUNITY

    if community_raw and ":" in community_raw:
        community_name, community_url = community_raw.split(":", 1)

    # Extract base version from Containerfile.j2 if present
    base_version = "15.1"  # fallback default
    cf_path = Path.cwd() / "Containerfile.j2"
    if cf_path.exists():
        import re
        match = re.search(r"ARG BASE_VERSION=(.*)", cf_path.read_text())
        if match:
            base_version = _normalize_base_version(match.group(1))

    context = {
        "name": cfg.image,
        "base_version": base_version,
        "title": meta.title,
        "description": meta.description,
        "category": meta.category,
        "upstream_url": meta.upstream_url,
        "web_url": meta.web_url,
        "freshports_url": meta.freshports_url,
        "user": meta.user,
        "jail_allow": jail_allow,
        "mlock": mlock,
        "sysvipc": sysvipc,
        "annotations": annotations,
        "upstream_binary": meta.upstream_binary,
        "icon": meta.icon,
        "logo": meta.logo,
        "logo_dark": meta.logo_dark,
        "healthcheck": meta.healthcheck,
        "notes": meta.notes,
        "readme": meta.readme,
        "community": community_raw,
        "community_name": community_name,
        "community_url": community_url,
        "registry": cfg.registry or "ghcr.io/daemonless",
        "repo_url": f"https://github.com/daemonless/{cfg.image}",
        "tags": [v.tag for v in cfg.variants] + [a for v in cfg.variants for a in (v.aliases or [])],
        "variants": [
            {
                "tag": v.tag,
                "aliases": v.aliases or [],
                "default": v.default,
                "args": v.args or {},
                "containerfile": v.containerfile or "Containerfile",
                "tag_desc": v.tag_desc,
            }
            for v in cfg.variants
        ],
        "default_tag": next(
            (a for v in cfg.variants if v.default for a in ["latest"] if a in v.aliases),
            cfg.variants[0].tag if cfg.variants else "latest",
        ),
        "architectures": cfg.architectures,
        "appjail": appjail_meta,
        "appjail_enabled": appjail_enabled,
        "bastille": bastille_meta,
        "bastille_enabled": bastille_enabled,
        "docs": meta.docs,
        "deprecated": meta.deprecated,
        "screenshots": _collect_screenshots(Path.cwd()),
        "cit_mode": cfg.test.mode if cfg.test else "none",
        "image_class": meta.image_class,
        "env": [],
        "volumes": [],
        "ports": [],
    }

    # Environment
    env_docs = {str(k): v for k, v in docs.get("env", {}).items()}

    # Ensure any explicitly documented env vars are included (critical for stacks)
    existing_env_names = {str(e["name"]) for e in cfg.env}
    for k, v in env_docs.items():
        if k not in existing_env_names:
            if isinstance(v, dict):
                cfg.env.append({"name": k, "default": str(v.get("default", ""))})
            else:
                cfg.env.append({"name": k, "default": ""})

    for e in cfg.env:
        name = e["name"]
        val = e["default"]

        display_val = val if val and val not in ['""', "''"] else ""
        if not display_val and any(x in name.upper() for x in ["PASS", "KEY", "SECRET", "TOKEN"]):
            display_val = f"<{name.upper()}>"

        desc = env_docs.get(str(name), "")
        if isinstance(desc, dict):
            display_val = display_val or str(desc.get("default", ""))
            desc = desc.get("desc", "")

        item = {"name": name, "default": display_val, "desc": desc}
        if name in ["PUID", "PGID", "TZ"]:
            item["placeholder"] = f"@{name}@"
        context["env"].append(item)

    # Volumes
    vol_docs = {str(k): v for k, v in docs.get("volumes", {}).items()}
    for v in cfg.volumes:
        src = v["source"]
        tgt = v["target"]

        clean_target = tgt.strip("/").replace("/", "_").replace("-", "_").replace(".", "_").upper()
        vol_info = vol_docs.get(str(tgt), "")
        desc = vol_info.get("desc", "") if isinstance(vol_info, dict) else str(vol_info)
        optional = vol_info.get("optional", False) if isinstance(vol_info, dict) else False

        if tgt in SHARED_PATHS:
            source_path = tgt.lstrip("/")
            placeholder = f"@{clean_target}_PATH@"
            root_var = None
        elif tgt == "/config":
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_CONFIG_PATH@"
            source_path = cfg.image
            root_var = CONFIG_ROOT_VAR
        elif src == tgt:
            # Source equals target — host path is the literal mount point, not user-configurable
            source_path = src
            root_var = None
            placeholder = src
        elif src.startswith("./") or src.startswith("."):
            clean_src = src.lstrip("./")
            source_path = f"{cfg.image}/{clean_src}"
            root_var = CONFIG_ROOT_VAR
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_{clean_src.upper().replace('-', '_')}_PATH@"
        else:
            subdir = tgt.rstrip("/").split("/")[-1]
            if len(cfg.volumes) == 1 and subdir in ("config", "data"):
                source_path = cfg.image
            else:
                source_path = f"{cfg.image}/{subdir}"
            root_var = CONFIG_ROOT_VAR
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_{subdir.upper().replace('-', '_')}_PATH@"

        context["volumes"].append({
            "path": tgt,
            "desc": desc,
            "optional": optional,
            "placeholder": placeholder,
            "source": source_path,
            "root_var": root_var,
            "options": v.get("options", "")
        })

    # Ports
    port_docs = {str(k): v for k, v in docs.get("ports", {}).items()}
    for p in cfg.ports:
        pub = p["published"]
        tgt = p["target"]
        proto = p["protocol"]

        context["ports"].append({
            "port": pub,
            "protocol": proto,
            "desc": port_docs.get(str(tgt), ""),
            "name": "web",
            "target": tgt
        })

    return context


def generate_appjail_files(
    cfg: Config,
    dest_dir: Path,
    *,
    image_ref: str | None = None,
) -> Path:
    """Render appjail-director.yml, .env, and Makejail into *dest_dir*.

    Per-file override: if ``.daemonless/appjail/<file>`` exists it is copied
    as-is; otherwise the bundled template is rendered.

    Parameters
    ----------
    cfg:
        Parsed build configuration.
    dest_dir:
        Directory to write files into (created if absent).
    image_ref:
        When set (test mode), the Makejail ``OPTION from=`` line points to
        this local image reference instead of the registry.
    """
    if jinja2 is None:
        raise ImportError("jinja2 is required for appjail file generation")

    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)

    override_dir = Path.cwd() / ".daemonless" / "appjail"
    env = _get_jinja_env(Path.cwd())
    if env is None:
        raise RuntimeError("Could not find dbuild templates")

    context = _enrich_metadata(cfg)
    if image_ref:
        context["image_ref"] = image_ref

    files = {
        "appjail-director.yml": "appjail-director.yml.j2",
        ".env":                  "appjail.env.j2",
        "Makejail":              "Makejail.j2",
    }

    for filename, template_name in files.items():
        override = override_dir / filename
        dest = dest_dir / filename
        if override.is_file():
            import shutil as _shutil
            _shutil.copy2(override, dest)
            log.info(f"AppJail: using override {override.relative_to(Path.cwd())}")
        else:
            try:
                tmpl = env.get_template(template_name)
                dest.write_text(tmpl.render(context))
            except jinja2.TemplateNotFound:
                log.warn(f"AppJail: template {template_name} not found, skipping")

    return dest_dir


def _readme_generation_mode(cfg: Config, base: Path) -> str:
    """Decide how README.md generation should behave.

    Returns one of:

    - ``"generate"``: render README.md from the bundled/override template.
    - ``"manual-override"``: ``docs: manual`` but a local ``README.j2`` exists,
      so it is still rendered (just from the repo override).
    - ``"skip"``: ``docs: manual`` with no local ``README.j2`` — README.md is
      hand-maintained and must not be generated or drift-checked.
    """
    is_manual = (cfg.metadata.docs == "manual" or
                 (isinstance(cfg.metadata.docs, dict) and cfg.metadata.docs.get("manual", False)))
    has_local_readme_j2 = (base / "README.j2").exists()
    if is_manual and not has_local_readme_j2:
        return "skip"
    if is_manual and has_local_readme_j2:
        return "manual-override"
    return "generate"


def render_generated(
    cfg: Config,
    args: argparse.Namespace,
    base: Path | None = None,
) -> tuple[dict[str, str], list[str]]:
    """Render the artifacts ``dbuild generate`` would write, in memory.

    This is the shared rendering core used by both :func:`run` (which writes
    the files) and the ``dbuild lint --check-generated`` drift check (which
    compares them to disk). Keeping a single code path guarantees the check
    reflects exactly what generation produces.

    Returns ``(outputs, errors)`` where *outputs* maps each output filename to
    its full file content (header included, matching what would be written) and
    *errors* lists per-file render failures. Only files that generation would
    actually write are present in *outputs* (e.g. a ``docs: manual`` image with
    no ``README.j2`` yields no ``README.md`` entry).
    """
    base = base or Path.cwd()
    outputs: dict[str, str] = {}
    errors: list[str] = []

    if jinja2 is None:
        return outputs, ["jinja2 is not installed"]

    community_override = getattr(args, "community", None)
    context = _enrich_metadata(cfg, community_override)

    env = _get_jinja_env(base)
    if env is None:
        return outputs, ["could not find dbuild templates"]

    # README.md — uses the ChoiceLoader so the bundled template is a fallback.
    if _readme_generation_mode(cfg, base) != "skip":
        try:
            template = env.get_template("README.j2")
            outputs["README.md"] = template.render(context, render_mode="github")
        except jinja2.TemplateNotFound:
            # Matches run(): warn + skip; README.md is left untouched.
            pass

    # Containerfiles — repo-only loader (local includes, no bundled fallback).
    for j2_path in sorted(base.glob("Containerfile*.j2")):
        out_name = j2_path.name.replace(".j2", "")
        try:
            repo_env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(base)))
            template = repo_env.get_template(j2_path.name)
            outputs[out_name] = (
                HEADER_TEMPLATE.format(source=j2_path.name) + template.render(context)
            )
        except Exception as e:
            errors.append(f"Failed to render {out_name}: {e}")

    return outputs, errors


def run(cfg: Config, args: argparse.Namespace) -> int:
    """Generate documentation and Containerfiles."""
    if jinja2 is None:
        log.error("Jinja2 is not installed. Code generation requires it.")
        log.info("Run: pip install jinja2")
        return 1

    base = Path.cwd()

    if cfg.metadata.deprecated is not None:
        dep = cfg.metadata.deprecated
        msg = f"Image '{cfg.image}' is deprecated"
        if dep.replacement:
            msg += f" — suggested replacement: {dep.replacement}"
        log.warn(msg)

    env = _get_jinja_env(base)
    if not env:
        log.error("Could not find dbuild templates.")
        return 1

    readme_mode = _readme_generation_mode(cfg, base)
    if readme_mode == "skip":
        log.info("Skipping README.md generation (docs: manual)")
    elif readme_mode == "manual-override":
        log.info("docs: manual — using local README.j2 override")

    outputs, errors = render_generated(cfg, args, base)

    if readme_mode != "skip" and "README.md" not in outputs:
        log.warn("README.j2 template not found, skipping README.md")

    for name, content in outputs.items():
        (base / name).write_text(content)
        log.step(f"Generated {name}")
    for err in errors:
        log.error(err)

    return 0


# ── Drift check (generate --check) ────────────────────────────────────

def _is_image_repo(path: Path) -> bool:
    return (path / "compose.yaml").exists() or (path / ".daemonless" / "config.yaml").exists()


def check_repo(repo_path: Path) -> tuple[list[str], list[str]]:
    """Compare a repo's on-disk generated artifacts against a fresh render.

    Re-renders ``README.md`` and ``Containerfile*`` through the same code path
    as generation (:func:`render_generated`) and compares the result to what is
    committed on disk. This catches the common case of a ``.j2`` template being
    edited without re-running ``dbuild generate``.

    Returns ``(stale, notes)``:

    - *stale*: files that are missing or differ from a fresh render. Each
      message includes the fix (``run dbuild generate``).
    - *notes*: informational messages (e.g. README check skipped because the
      registry could not be resolved locally — see below).

    ``Containerfile*`` outputs use a literal ``FROM`` registry, so they are
    deterministic regardless of where the check runs. ``README.md`` embeds the
    registry derived from the git remote (or ``DBUILD_REGISTRY``); when neither
    is available the rendered registry would differ from the committed file, so
    the README comparison is skipped rather than reported as a false positive.
    """
    from dbuild import config as _config

    stale: list[str] = []
    notes: list[str] = []

    has_templates = (
        any(repo_path.glob("Containerfile*.j2"))
        or (repo_path / "README.j2").exists()
    )
    if not has_templates:
        return stale, notes

    cwd = Path.cwd()
    try:
        # _enrich_metadata reads Path.cwd() (base version, screenshots), so
        # render from inside the repo and always restore the original cwd.
        os.chdir(repo_path)
        cfg = _config.load(repo_path)
        args_ns = argparse.Namespace(community=None)
        outputs, render_errors = render_generated(cfg, args_ns, repo_path)

        stale.extend(render_errors)

        registry_confident = bool(
            os.environ.get("DBUILD_REGISTRY") or _config._git_remote_org()
        )

        for name, content in outputs.items():
            if name == "README.md" and not registry_confident:
                notes.append(
                    "README.md drift check skipped: registry unresolved"
                    " (no git remote / DBUILD_REGISTRY) — verify on CI/saturn"
                )
                continue
            dest = repo_path / name
            if not dest.exists():
                stale.append(f"{name} is missing — run dbuild generate")
            elif dest.read_text() != content:
                stale.append(f"{name} is out of date — run dbuild generate")
    except Exception as e:  # one bad repo must not abort the sweep
        stale.append(f"could not render generated files: {e}")
    finally:
        os.chdir(cwd)

    return stale, notes


def run_check(args: argparse.Namespace) -> int:
    """``dbuild generate --check``: fail if committed generated files are stale.

    Checks the current repo if run from an image directory, or every
    subdirectory if run from a workspace root (mirroring ``dbuild lint``).
    """
    cwd = Path.cwd()
    repos = [cwd] if _is_image_repo(cwd) else sorted(
        p for p in cwd.iterdir() if p.is_dir()
    )

    all_stale: dict[str, list[str]] = {}
    readme_skipped = 0
    for repo in repos:
        stale, notes = check_repo(repo)
        if stale:
            all_stale[repo.name] = stale
        if any("README" in n for n in notes):
            readme_skipped += 1

    if readme_skipped:
        log.info(
            f"README.md drift check skipped for {readme_skipped}"
            f" repo{'s' if readme_skipped != 1 else ''}"
            " (registry unresolved locally; verify on CI/saturn)."
        )

    if all_stale:
        print("\nOUT OF DATE:")
        print("=" * 60)
        for name, items in sorted(all_stale.items()):
            print(f"\n{name}:")
            for item in items:
                print(f"  - {item}")
        n = len(all_stale)
        print(
            f"\n{n} repo{'s' if n != 1 else ''} out of date"
            " — run 'dbuild generate' to update"
        )
        return 1

    print("All generated files are up to date")
    return 0
