"""Documentation and Containerfile generation from compose.yaml metadata.
"""

from __future__ import annotations

import argparse
from datetime import date
from pathlib import Path
from typing import Any

try:
    import jinja2
except ImportError:
    jinja2 = None

import dataclasses

import dbuild
from dbuild import log
from dbuild.config import (
    DEFAULT_COMMUNITY,
    AppTestConfig,
    Config,
    DeprecationInfo,
    Metadata,
    Variant,
)

# Constants for placeholder generation
CONFIG_ROOT_VAR = "@CONTAINER_CONFIG_ROOT@"
SHARED_PATHS = ["/downloads", "/movies", "/tv", "/music", "/books", "/media"]

HEADER_TEMPLATE = """# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: {source}
# --------------------------------------------------------------------------

"""

README_HEADER = """<!--
THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
Source: dbuild templates
-->

"""


# ── Documentation helpers ─────────────────────────────────────────────

def _fields_for_docs(cls) -> list[tuple[str, str, str]]:
    """Extract (field, display_default, description) from a dataclass.

    Only fields with a ``desc`` key in their metadata are included,
    allowing internal fields to be silently skipped.
    """
    result = []
    for f in dataclasses.fields(cls):
        desc = f.metadata.get("desc", "")
        if not desc:
            continue
        if "display_default" in f.metadata:
            default = f.metadata["display_default"]
        elif f.default is not dataclasses.MISSING:
            val = f.default
            if val is None:
                default = "None"
            elif isinstance(val, bool):
                default = str(val).lower()
            elif isinstance(val, str):
                default = f'"{val}"' if val else '""'
            else:
                default = str(val)
        else:
            default = "(required)"
        result.append((f.name, default, desc))
    return result


# ── Extended Documentation Content ────────────────────────────────────

DOCS_CONTENT = {
    "DESCRIPTION": (
        "dbuild provides a streamlined interface for creating and managing OCI-compliant "
        "containers that run natively in FreeBSD Jails. It eliminates the friction of "
        "configuring ocijail, networking, and jail templates by using a 'Registry-First' "
        "approach. Configuration is automatically derived from Git remotes and standard "
        "Compose files, allowing for reproducible builds across local and CI environments."
    ),
    "ENVIRONMENT": {
        "DBUILD_REGISTRY": "Override the target container registry (e.g., ghcr.io/myorg).",
        "GITHUB_TOKEN": "Authentication token for GitHub Packages and build secrets.",
        "GITHUB_ACTOR": "The username associated with GITHUB_TOKEN.",
        "DOCKERHUB_USERNAME": "Enable mirroring by providing a Docker Hub username.",
        "DOCKERHUB_TOKEN": "Personal access token for Docker Hub mirroring.",
        "CHROME_BIN": "Path to the Chrome/Chromium binary for screenshot testing.",
    },
    "FILES": {
        "compose.yaml": "The primary source of truth for metadata and documentation.",
        ".daemonless/config.yaml": "Project-specific build and test overrides.",
        "/usr/local/etc/daemonless.yaml": "Global templates for shared build variants.",
    },
    "EXAMPLES": [
        ("Build and push all variants", "dbuild build --push"),
        ("Initialize from a FreeBSD Port", "dbuild init --freebsd-port net-p2p/transmission"),
        ("Run specific tests", "dbuild test --variant pkg"),
    ],
    "EXIT_STATUS": {
        "0": "Success.",
        "1": "Build, test, or system failure.",
        "2": "Command-line usage error (invalid flags or arguments).",
    },
    "METADATA_FIELDS": _fields_for_docs(Metadata),
    "BUILD_FIELDS": [
        # No BuildConfig dataclass yet — these are parsed from a raw dict in load().
        ("pkg_name",      "None",        "Default FreeBSD package name for version extraction across all variants"),
        ("architectures", '["amd64"]',   'List of architectures to build (e.g. `["amd64", "arm64"]`)'),
    ],
    "VARIANT_FIELDS":     _fields_for_docs(Variant),
    "CIT_FIELDS":         _fields_for_docs(AppTestConfig),
    "DEPRECATION_FIELDS": _fields_for_docs(DeprecationInfo),
}


def generate_manpage(parser: argparse.ArgumentParser) -> str:
    """Generate a ROFF format man page from the CLI parser."""
    today = date.today().strftime("%Y-%m-%d")
    output = []
    output.append(f'.TH DBUILD 1 "{today}" "dbuild {dbuild.VERSION}" "User Commands"')
    output.append(".SH NAME")
    output.append("dbuild \\- FreeBSD OCI container image build tool")
    output.append(".SH SYNOPSIS")
    output.append(".B dbuild")
    output.append("[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR...]")

    output.append(".SH DESCRIPTION")
    output.append(DOCS_CONTENT["DESCRIPTION"])

    subparser_actions = [
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    ]
    for subparser_action in subparser_actions:
        output.append(".SH COMMANDS")
        for choice, subparser in sorted(subparser_action.choices.items()):
            if choice == "docs":
                continue
            output.append(".TP")
            output.append(f"\\fB{choice}\\fR")
            desc = subparser.description or subparser.help
            output.append(desc)

            unique_actions = []
            seen = set()
            for action in subparser._option_string_actions.values():
                if action not in seen:
                    unique_actions.append(action)
                    seen.add(action)

            if unique_actions:
                output.append(".RS")
                for action in unique_actions:
                    opts = ", ".join(f"\\fB{o}\\fR" for o in action.option_strings)
                    help_text = (action.help or "").replace("%(default)s", str(action.default))
                    output.append(".TP")
                    output.append(opts)
                    output.append(help_text)
                output.append(".RE")

    output.append(".SH ENVIRONMENT")
    for var, desc in DOCS_CONTENT["ENVIRONMENT"].items():
        output.append(".TP")
        output.append(f"\\fI{var}\\fR")
        output.append(desc)

    output.append(".SH FILES")
    for file, desc in DOCS_CONTENT["FILES"].items():
        output.append(".TP")
        output.append(f"\\fI{file}\\fR")
        output.append(desc)

    output.append(".SH EXAMPLES")
    for title, cmd in DOCS_CONTENT["EXAMPLES"]:
        output.append(f"{title}:")
        output.append(".IP")
        output.append(f"dbuild {cmd.replace('dbuild ', '')}")

    output.append(".SH EXIT STATUS")
    for code, desc in DOCS_CONTENT["EXIT_STATUS"].items():
        output.append(".TP")
        output.append(f"\\fB{code}\\fR")
        output.append(desc)

    output.append(".SH SEE ALSO")
    output.append(".UR https://daemonless.io/guides/dbuild/")
    output.append("Full web documentation")
    output.append(".UE")

    return "\n".join(output)


def _get_jinja_env(base: Path) -> jinja2.Environment | None:
    """Create Jinja2 environment with override priority:
    1. repo root (README.j2 alongside Containerfile.j2)
    2. .daemonless/templates/
    3. bundled dbuild templates
    """
    if jinja2 is None:
        return None

    search_paths = [
        base,
        base / ".daemonless" / "templates",
        Path(__file__).parent / "templates",
    ]
    # Filter to existing directories
    loaders = [jinja2.FileSystemLoader(str(p)) for p in search_paths if p.is_dir()]
    if not loaders:
        return None

    return jinja2.Environment(loader=jinja2.ChoiceLoader(loaders))


_SCREENSHOT_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".svg", ".mp4", ".webm"}


def _collect_screenshots(base: Path) -> list[str]:
    """Return sorted relative paths for files in .daemonless/screenshots/."""
    shots_dir = base / ".daemonless" / "screenshots"
    if not shots_dir.is_dir():
        return []
    return sorted(
        str(p.relative_to(base))
        for p in shots_dir.iterdir()
        if p.is_file() and p.suffix.lower() in _SCREENSHOT_EXTS
    )


def _enrich_metadata(cfg: Config, community_override: str | None = None) -> dict[str, Any]:
    """Build a context dict for templates with enriched env/vol/port data from Config."""
    meta = cfg.metadata
    docs = meta.docs if isinstance(meta.docs, dict) else {}

    # Extract jail allow.* parameters from annotations
    annotations = cfg.test.annotations if cfg.test else []
    jail_allow = [
        a.split("=")[0].replace("org.freebsd.jail.", "")
        for a in annotations
        if "org.freebsd.jail.allow." in a and "=true" in a.lower()
    ]
    mlock = "allow.mlock" in jail_allow
    sysvipc = "allow.sysvipc" in jail_allow

    # Check for AppJail support
    # meta.appjail is None = disabled, {} = bare/default, {...} = custom config
    appjail_meta = meta.appjail if hasattr(meta, "appjail") else None
    appjail_enabled = appjail_meta is not None or any(
        "io.daemonless.appjail" in a for a in annotations
    )

    # Community: Use CLI override, metadata if set (Format: Name:URL), or default to Daemonless Discord.
    community_name = ""
    community_url = ""
    community_raw = community_override or meta.community
    if not community_raw and "daemonless" in cfg.registry.lower():
        community_raw = DEFAULT_COMMUNITY

    if community_raw and ":" in community_raw:
        community_name, community_url = community_raw.split(":", 1)

    context = {
        "name": cfg.image,
        "title": meta.title,
        "description": meta.description,
        "category": meta.category,
        "upstream_url": meta.upstream_url,
        "web_url": meta.web_url,
        "freshports_url": meta.freshports_url,
        "user": meta.user,
        "jail_allow": jail_allow,
        "mlock": mlock,
        "sysvipc": sysvipc,
        "annotations": annotations,
        "upstream_binary": meta.upstream_binary,
        "icon": meta.icon,
        "logo": meta.logo,
        "logo_dark": meta.logo_dark,
        "healthcheck": meta.healthcheck,
        "notes": meta.notes,
        "community": community_raw,
        "community_name": community_name,
        "community_url": community_url,
        "registry": cfg.registry or "ghcr.io/daemonless",
        "repo_url": f"https://github.com/daemonless/{cfg.image}",
        "tags": [v.tag for v in cfg.variants] + [a for v in cfg.variants for a in (v.aliases or [])],
        "variants": [
            {
                "tag": v.tag,
                "aliases": v.aliases or [],
                "default": v.default,
                "args": v.args or {},
                "containerfile": v.containerfile or "Containerfile",
                "tag_desc": v.tag_desc,
            }
            for v in cfg.variants
        ],
        "default_tag": next(
            (a for v in cfg.variants if v.default for a in ["latest"] if a in v.aliases),
            cfg.variants[0].tag if cfg.variants else "latest",
        ),
        "architectures": cfg.architectures,
        "appjail": appjail_meta,
        "appjail_enabled": appjail_enabled,
        "docs": meta.docs,
        "deprecated": meta.deprecated,
        "screenshots": _collect_screenshots(Path.cwd()),
        "cit_mode": cfg.test.mode if cfg.test else "none",
        "image_class": meta.image_class,
        "env": [],
        "volumes": [],
        "ports": [],
    }

    # Environment
    env_docs = {str(k): v for k, v in docs.get("env", {}).items()}
    for e in cfg.env:
        name = e["name"]
        val = e["default"]

        display_val = val if val and val not in ['""', "''"] else ""
        if not display_val and any(x in name.upper() for x in ["PASS", "KEY", "SECRET", "TOKEN"]):
            display_val = f"<{name.upper()}>"

        item = {"name": name, "default": display_val, "desc": env_docs.get(str(name), "")}
        if name in ["PUID", "PGID", "TZ"]:
            item["placeholder"] = f"@{name}@"
        context["env"].append(item)

    # Volumes
    vol_docs = {str(k): v for k, v in docs.get("volumes", {}).items()}
    for v in cfg.volumes:
        src = v["source"]
        tgt = v["target"]

        clean_target = tgt.strip("/").replace("/", "_").replace("-", "_").upper()
        vol_info = vol_docs.get(str(tgt), "")
        desc = vol_info.get("desc", "") if isinstance(vol_info, dict) else str(vol_info)
        optional = vol_info.get("optional", False) if isinstance(vol_info, dict) else False

        if tgt in SHARED_PATHS:
            source_path = tgt.lstrip("/")
            placeholder = f"@{clean_target}_PATH@"
            root_var = None
        elif tgt == "/config":
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_CONFIG_PATH@"
            source_path = cfg.image
            root_var = CONFIG_ROOT_VAR
        elif src.startswith("./") or src.startswith("."):
            clean_src = src.lstrip("./")
            source_path = f"{cfg.image}/{clean_src}"
            root_var = CONFIG_ROOT_VAR
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_{clean_src.upper().replace('-', '_')}_PATH@"
        else:
            source_path = f"{cfg.image}{tgt}"
            root_var = CONFIG_ROOT_VAR
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_{clean_target}_PATH@"

        context["volumes"].append({
            "path": tgt,
            "desc": desc,
            "optional": optional,
            "placeholder": placeholder,
            "source": source_path,
            "root_var": root_var
        })

    # Ports
    port_docs = {str(k): v for k, v in docs.get("ports", {}).items()}
    for p in cfg.ports:
        pub = p["published"]
        tgt = p["target"]
        proto = p["protocol"]

        context["ports"].append({
            "port": pub,
            "protocol": proto,
            "desc": port_docs.get(str(tgt), ""),
            "name": "web",
            "target": tgt
        })

    return context


def generate_appjail_files(
    cfg: Config,
    dest_dir: Path,
    *,
    image_ref: str | None = None,
) -> Path:
    """Render appjail-director.yml, .env, and Makejail into *dest_dir*.

    Per-file override: if ``.daemonless/appjail/<file>`` exists it is copied
    as-is; otherwise the bundled template is rendered.

    Parameters
    ----------
    cfg:
        Parsed build configuration.
    dest_dir:
        Directory to write files into (created if absent).
    image_ref:
        When set (test mode), the Makejail ``OPTION from=`` line points to
        this local image reference instead of the registry.
    """
    if jinja2 is None:
        raise ImportError("jinja2 is required for appjail file generation")

    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)

    override_dir = Path.cwd() / ".daemonless" / "appjail"
    env = _get_jinja_env(Path.cwd())
    if env is None:
        raise RuntimeError("Could not find dbuild templates")

    context = _enrich_metadata(cfg)
    if image_ref:
        context["image_ref"] = image_ref

    files = {
        "appjail-director.yml": "appjail-director.yml.j2",
        ".env":                  "appjail.env.j2",
        "Makejail":              "Makejail.j2",
    }

    for filename, template_name in files.items():
        override = override_dir / filename
        dest = dest_dir / filename
        if override.is_file():
            import shutil as _shutil
            _shutil.copy2(override, dest)
            log.info(f"AppJail: using override {override.relative_to(Path.cwd())}")
        else:
            try:
                tmpl = env.get_template(template_name)
                dest.write_text(tmpl.render(context))
            except jinja2.TemplateNotFound:
                log.warn(f"AppJail: template {template_name} not found, skipping")

    return dest_dir


def run(cfg: Config, args: argparse.Namespace) -> int:
    """Generate documentation and Containerfiles."""
    if jinja2 is None:
        log.error("Jinja2 is not installed. Code generation requires it.")
        log.info("Run: pip install jinja2")
        return 1

    base = Path.cwd()
    community_override = getattr(args, "community", None)
    context = _enrich_metadata(cfg, community_override)

    if cfg.metadata.deprecated is not None:
        dep = cfg.metadata.deprecated
        msg = f"Image '{cfg.image}' is deprecated"
        if dep.replacement:
            msg += f" — suggested replacement: {dep.replacement}"
        log.warn(msg)

    env = _get_jinja_env(base)
    if not env:
        log.error("Could not find dbuild templates.")
        return 1

    # 1. Generate README.md (if docs: manual isn't set, or if a local README.j2 exists)
    is_manual = (cfg.metadata.docs == "manual" or
                 (isinstance(cfg.metadata.docs, dict) and cfg.metadata.docs.get("manual", False)))
    has_local_readme_j2 = (base / "README.j2").exists()

    if is_manual and not has_local_readme_j2:
        log.info("Skipping README.md generation (docs: manual)")
    else:
        if is_manual and has_local_readme_j2:
            log.info("docs: manual — using local README.j2 override")
        try:
            template = env.get_template("README.j2")
            content = template.render(context, render_mode="github")
            (base / "README.md").write_text(content)
            log.step("Generated README.md")
        except jinja2.TemplateNotFound:
            log.warn("README.j2 template not found, skipping README.md")

    # 2. Generate Containerfiles from .j2 templates
    for j2_path in base.glob("Containerfile*.j2"):
        out_name = j2_path.name.replace(".j2", "")
        try:
            # We use a separate env for local repo files to allow including local templates
            repo_env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(base)))
            template = repo_env.get_template(j2_path.name)

            content = HEADER_TEMPLATE.format(source=j2_path.name) + template.render(context)
            (base / out_name).write_text(content)
            log.step(f"Generated {out_name}")
        except Exception as e:
            log.error(f"Failed to generate {out_name}: {e}")

    return 0
