"""Documentation and Containerfile generation from compose.yaml metadata.
"""

from __future__ import annotations

import argparse
import os
import re
from datetime import date
from pathlib import Path
from typing import Any

from .config import _confident_prefix

try:
    import jinja2
except ImportError:
    jinja2 = None

import dataclasses

import dbuild
from dbuild import choices as choices_mod
from dbuild import log
from dbuild.config import (
    DEFAULT_COMMUNITY,
    AppTestConfig,
    Config,
    DeprecationInfo,
    Metadata,
    Variant,
)

# Constants for placeholder generation
CONFIG_ROOT_VAR = "@CONTAINER_CONFIG_ROOT@"
SHARED_PATHS = ["/downloads", "/movies", "/tv", "/music", "/books", "/media"]

HEADER_TEMPLATE = """# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: {source}
# --------------------------------------------------------------------------

"""

README_HEADER = """<!--
THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
Source: dbuild templates
-->

"""


# ── Documentation helpers ─────────────────────────────────────────────

def _fields_for_docs(cls) -> list[tuple[str, str, str]]:
    """Extract (field, display_default, description) from a dataclass.

    Only fields with a ``desc`` key in their metadata are included,
    allowing internal fields to be silently skipped.
    """
    result = []
    for f in dataclasses.fields(cls):
        desc = f.metadata.get("desc", "")
        if not desc:
            continue
        if "display_default" in f.metadata:
            default = f.metadata["display_default"]
        elif f.default is not dataclasses.MISSING:
            val = f.default
            if val is None:
                default = "None"
            elif isinstance(val, bool):
                default = str(val).lower()
            elif isinstance(val, str):
                default = f'"{val}"' if val else '""'
            else:
                default = str(val)
        else:
            default = "(required)"
        result.append((f.name, default, desc))
    return result


# ── Extended Documentation Content ────────────────────────────────────

def _global_config_doc_path() -> str:
    """Return the global config path for display in generated docs.

    Unlike dbuild.config._global_config_path(), this does NOT fall back to
    sys.prefix. During an isolated PEP 517 build that doesn't export
    PREFIX (e.g. a port build), sys.prefix resolves to pip/build's
    throwaway virtualenv, not any real install location -- showing that
    path would be actively wrong, not just imprecise. When the prefix
    can't be determined confidently, show the literal placeholder instead.
    """
    prefix_path = _confident_prefix()
    if prefix_path is None:
        return "$PREFIX/etc/daemonless.yaml"
    return str(prefix_path / "etc" / "daemonless.yaml")


DOCS_CONTENT = {
    "DESCRIPTION": (
        "dbuild provides a streamlined interface for creating and managing OCI-compliant "
        "containers that run natively in FreeBSD Jails. It eliminates the friction of "
        "configuring ocijail, networking, and jail templates by using a 'Registry-First' "
        "approach. Configuration is automatically derived from Git remotes and standard "
        "Compose files, allowing for reproducible builds across local and CI environments."
    ),
    "ENVIRONMENT": {
        "DBUILD_REGISTRY": "Override the target container registry (e.g., ghcr.io/myorg).",
        "GITHUB_TOKEN": "Authentication token for GitHub Packages and build secrets.",
        "GITHUB_ACTOR": "The username associated with GITHUB_TOKEN.",
        "DOCKERHUB_USERNAME": "Enable mirroring by providing a Docker Hub username.",
        "DOCKERHUB_TOKEN": "Personal access token for Docker Hub mirroring.",
        "CHROME_BIN": "Path to the Chrome/Chromium binary for screenshot testing.",
    },
    "FILES": {
        "compose.yaml": "The primary source of truth for metadata and documentation.",
        ".daemonless/config.yaml": "Project-specific build and test overrides.",
    },
    "GLOBAL_CONFIGURATION_EXAMPLE": """pkg_cache_url: pkg-cache.example.lan:8080""",
    "EXAMPLES": [
        ("Build and push all variants", "dbuild build --push"),
        ("Initialize from a FreeBSD Port", "dbuild init --freebsd-port net-p2p/transmission"),
        ("Run specific tests", "dbuild test --variant pkg"),
    ],
    "EXIT_STATUS": {
        "0": "Success.",
        "1": "Build, test, or system failure.",
        "2": "Command-line usage error (invalid flags or arguments).",
    },
    "METADATA_FIELDS": _fields_for_docs(Metadata),
    "BUILD_FIELDS": [
        # No BuildConfig dataclass yet — these are parsed from a raw dict in load().
        ("pkg_name",      "None",        "Default FreeBSD package name (auto-injected as --build-arg PKG_NAME and used for version extraction across variants)"),
        ("architectures", '["amd64"]',   'List of architectures to build (e.g. `["amd64", "arm64"]`)'),
    ],
    "VARIANT_FIELDS":     _fields_for_docs(Variant),
    "CIT_FIELDS":         _fields_for_docs(AppTestConfig),
    "DEPRECATION_FIELDS": _fields_for_docs(DeprecationInfo),
}


def generate_manpage(parser: argparse.ArgumentParser) -> str:
    """Generate a ROFF format man page from the CLI parser."""
    today = date.today().strftime("%Y-%m-%d")
    output = []
    output.append(f'.TH DBUILD 1 "{today}" "dbuild {dbuild.VERSION}" "User Commands"')
    output.append(".SH NAME")
    output.append("dbuild \\- FreeBSD OCI container image build tool")
    output.append(".SH SYNOPSIS")
    output.append(".B dbuild")
    output.append("[\\fIOPTIONS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR...]")

    output.append(".SH DESCRIPTION")
    output.append(DOCS_CONTENT["DESCRIPTION"])

    subparser_actions = [
        action for action in parser._actions
        if isinstance(action, argparse._SubParsersAction)
    ]
    for subparser_action in subparser_actions:
        output.append(".SH COMMANDS")
        for choice, subparser in sorted(subparser_action.choices.items()):
            if choice == "docs":
                continue
            output.append(".TP")
            output.append(f"\\fB{choice}\\fR")
            desc = subparser.description or subparser.help
            output.append(desc)

            unique_actions = []
            seen = set()
            for action in subparser._option_string_actions.values():
                if action not in seen:
                    unique_actions.append(action)
                    seen.add(action)

            if unique_actions:
                output.append(".RS")
                for action in unique_actions:
                    opts = ", ".join(f"\\fB{o}\\fR" for o in action.option_strings)
                    help_text = (action.help or "").replace("%(default)s", str(action.default))
                    output.append(".TP")
                    output.append(opts)
                    output.append(help_text)
                output.append(".RE")

    output.append(".SH ENVIRONMENT")
    for var, desc in DOCS_CONTENT["ENVIRONMENT"].items():
        output.append(".TP")
        output.append(f"\\fI{var}\\fR")
        output.append(desc)

    output.append(".SH FILES")
    for file, desc in DOCS_CONTENT["FILES"].items():
        output.append(".TP")
        output.append(f"\\fI{file}\\fR")
        output.append(desc)

    global_config_path = _global_config_doc_path()
    output.append(".TP")
    output.append(f"\\fI{global_config_path}\\fR")
    output.append(
        "Optional host-local defaults, including pkg_cache_url for local pkg-cache injection."
    )

    output.append(".SH GLOBAL CONFIGURATION")
    output.append(
        f"The \\fI{global_config_path}\\fR file is an optional host-local "
        "config file for settings that apply on this builder, not in every "
        "image repo. To use a local pkg cache, set \\fIpkg_cache_url\\fR. "
        "dbuild injects that value into builds as \\fIPKG_CACHE_URL\\fR, "
        "and opt-in Containerfiles can use it to point FreeBSD pkg at the "
        "local cache during build. If the file or key is missing, nothing "
        "is injected."
    )
    output.append(".PP")
    output.append(f"Example \\fI{global_config_path}\\fR:")
    output.append(".IP")
    output.append(".nf")
    output.append(DOCS_CONTENT["GLOBAL_CONFIGURATION_EXAMPLE"])
    output.append(".fi")

    output.append(".SH EXAMPLES")
    for title, cmd in DOCS_CONTENT["EXAMPLES"]:
        output.append(f"{title}:")
        output.append(".IP")
        output.append(f"dbuild {cmd.replace('dbuild ', '')}")

    output.append(".SH EXIT STATUS")
    for code, desc in DOCS_CONTENT["EXIT_STATUS"].items():
        output.append(".TP")
        output.append(f"\\fB{code}\\fR")
        output.append(desc)

    output.append(".SH SEE ALSO")
    output.append(".UR https://daemonless.io/guides/dbuild/")
    output.append("Full web documentation")
    output.append(".UE")

    return "\n".join(output)


def _get_jinja_env(base: Path) -> jinja2.Environment | None:
    """Create Jinja2 environment with override priority:
    1. repo root (README.j2 alongside Containerfile.j2)
    2. .daemonless/templates/
    3. bundled dbuild templates
    """
    if jinja2 is None:
        return None

    search_paths = [
        base,
        base / ".daemonless" / "templates",
        Path(__file__).parent / "templates",
    ]
    # Filter to existing directories
    loaders = [jinja2.FileSystemLoader(str(p)) for p in search_paths if p.is_dir()]
    if not loaders:
        return None

    return jinja2.Environment(loader=jinja2.ChoiceLoader(loaders))


_SCREENSHOT_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".svg", ".mp4", ".webm"}


def _collect_screenshots(base: Path) -> list[str]:
    """Return sorted relative paths for files in .daemonless/screenshots/."""
    shots_dir = base / ".daemonless" / "screenshots"
    if not shots_dir.is_dir():
        return []
    return sorted(
        str(p.relative_to(base))
        for p in shots_dir.iterdir()
        if p.is_file() and p.suffix.lower() in _SCREENSHOT_EXTS
    )


def _doc_alias(alias: str) -> str:
    """README form of an alias: ``{version}`` shows as ``<version>``."""
    return alias.replace("{version}", "<version>")


def _normalize_base_version(raw: str, default: str = "15.1") -> str:
    """Turn a BASE_VERSION arg (which may be a pkg tag) into a FreeBSD release:
    '15-pkg' -> '15', '15.1-latest' -> '15.1', '15.1-pkg-latest' -> '15.1',
    bare 'latest'/'' -> default. Suffix order matters (-pkg-latest first)."""
    v = raw.strip().strip('"\'')
    for suffix in ("-pkg-latest", "-pkg", "-latest"):
        if v.endswith(suffix):
            v = v[: -len(suffix)]
            break
    return v if v and v != "latest" else default


def _site_placeholders(text: str, env_file: bool = False) -> str:
    """Put the docs site's placeholders into a repo's own compose or .env.

    /containers -> @CONTAINER_CONFIG_ROOT@, PUID/PGID=1000 -> @PUID@/@PGID@,
    and in a .env the TZ line -> TZ=@TZ@, so the settings panel fills them
    in as it does on a one-service page.
    """
    if not text:
        return ""
    text = re.sub(r"/containers(?=/)", CONFIG_ROOT_VAR, text)
    text = re.sub(r"(?m)(\bPUID=)1000\b", r"\g<1>@PUID@", text)
    text = re.sub(r"(?m)(\bPGID=)1000\b", r"\g<1>@PGID@", text)
    if env_file:
        text = re.sub(r"(?m)^#?\s*TZ=\S*$", "TZ=@TZ@", text)
    return text


def _combinations(cfg: Config) -> list[list[tuple[Any, Any]]]:
    """Every way of answering the choices: one option per choice, every
    combination, the all-default one first."""
    import itertools

    cs = cfg.metadata.choices
    if not cs:
        return []
    ordered = [sorted(c.options, key=lambda o: o.id != c.default) for c in cs]
    return [list(zip(cs, picks, strict=True)) for picks in itertools.product(*ordered)]


def _choice_variants(cfg: Config) -> list[tuple[list[tuple[Any, Any]], str, str]]:
    """(pairs, compose text, env text) for every combination that is not the
    default. The files people copy, one per combination."""
    out = []
    for pairs in _combinations(cfg):
        if all(o.id == c.default for c, o in pairs):
            continue
        opts = [o for _, o in pairs]
        compose_text = choices_mod.flatten_compose(cfg.compose_text, cfg.compose_data, opts)
        out.append((pairs, compose_text, choices_mod.env_with_options(cfg.example_env, pairs)))
    return out


def _authored_director(cfg: Config) -> dict | None:
    """The complete appjail.director an author wrote (immich), or None."""
    aj = cfg.metadata.appjail if isinstance(cfg.metadata.appjail, dict) else None
    d = (aj or {}).get("director")
    return d if isinstance(d, dict) and d.get("services") else None


def _director_for_option(director: dict, cfg: Config, option) -> dict:
    """An authored director with only the services the chosen options run:
    the dropped ones out, profiled ones in only when an option names their
    profile. Service names match the compose's, so the compose's profiles
    say which is which."""
    services = cfg.compose_data.get("services") or {}
    options = choices_mod._as_list(option)
    profiles = {o.profile for o in options if o.profile}
    drop = {d for o in options for d in o.drop}
    out = dict(director)
    kept = {}
    for name, svc in (director.get("services") or {}).items():
        if name in drop:
            continue
        svc_profiles = {str(p) for p in ((services.get(name) or {}).get("profiles") or [])}
        if svc_profiles and not (svc_profiles & profiles):
            continue
        kept[name] = svc
    out["services"] = kept
    # Volumes only the kept services mount.
    used = set()
    for svc in kept.values():
        for v in (svc or {}).get("volumes") or []:
            if isinstance(v, dict):
                used.update(v.keys())
            elif isinstance(v, str):
                used.add(v.split(":")[0].strip())
    if isinstance(director.get("volumes"), dict):
        out["volumes"] = {k: v for k, v in director["volumes"].items() if k in used}
    return out


def _sidecar_templates(cfg: Config) -> list[dict[str, str]]:
    """Jail templates the authored bundle ships beside director.yml
    (appjail.depends_on[].template), with their text, for the README."""
    aj = cfg.metadata.appjail if isinstance(cfg.metadata.appjail, dict) else {}
    out = []
    for dep in (aj or {}).get("depends_on") or []:
        tpl = dep.get("template") if isinstance(dep, dict) else None
        if not tpl:
            continue
        path = Path.cwd() / tpl
        if path.is_file():
            out.append({"file": tpl, "text": path.read_text().rstrip("\n")})
    return out


def _stack_parts(cfg: Config) -> list[dict[str, str]]:
    """The services of a stack with their images and roles (docs.services),
    for the Parts table; a daemonless image links to its own page."""
    if not cfg.compose_text:
        return []
    docs = cfg.metadata.docs if isinstance(cfg.metadata.docs, dict) else {}
    roles = {str(k): str(v) for k, v in (docs.get("services") or {}).items()}
    out = []
    for name, svc in (cfg.compose_data.get("services") or {}).items():
        img = str((svc or {}).get("image", ""))
        repo = img.split(":")[0]
        page = repo.split("/")[-1] if repo.startswith("ghcr.io/daemonless/") else ""
        profiles = [str(p) for p in ((svc or {}).get("profiles") or [])]
        out.append({"name": name, "image": img, "desc": roles.get(name, ""), "page": page,
                    "when": "" if not profiles else "with " + ", ".join(profiles)})
    return out


def _choice_context(cfg: Config, context_env: list[dict[str, Any]]) -> dict[str, Any]:
    """The choices as the templates read them.

    ``combos`` is one entry per way of answering every choice, the default
    first, each with the files it needs in both renderings. ``tree`` nests
    them choice by choice for the site's tabs: pick the first choice, then
    the next inside it, and the leaf is the combination's files. The GitHub
    README lists ``combos`` flat. ``choices`` is the declaration itself.
    """
    if not cfg.metadata.choices or not cfg.compose_text:
        return {"choices": [], "combos": [], "tree": None}
    import re as _re

    import yaml  # lazy, as everywhere in this module: the wheel build imports it without yaml

    variants = {choices_mod.variant_suffix(pairs): (ct, et) for pairs, ct, et in _choice_variants(cfg)}
    engine_services = {ENGINE["service"] for ENGINE in choices_mod.ENGINES.values() if ENGINE.get("service")}
    authored = _authored_director(cfg)
    combos = []
    for pairs in _combinations(cfg):
        opts = [o for _, o in pairs]
        suffix = choices_mod.variant_suffix(pairs)
        is_default = suffix == ""
        if is_default:
            ct, et = choices_mod.flatten_compose(cfg.compose_text, cfg.compose_data, None), cfg.example_env
            compose_file, env_file = "compose.yaml", "example.env"
        else:
            ct, et = variants[suffix]
            compose_file, env_file = f"compose.{suffix}.yaml", f"example.{suffix}.env"
        # The AppJail side: the template director grows each engine's jail,
        # the .env takes every option's values with the host being the jail's
        # name.
        aj = dict(cfg.metadata.appjail) if isinstance(cfg.metadata.appjail, dict) else {}
        values: dict[str, str] = {}
        asks = []
        for o in opts:
            if o.director_dep:
                aj["depends_on"] = [*(aj.get("depends_on") or []), o.director_dep]
            values.update(o.env)
            values.update(o.env_appjail)
            for ln in o.env_lines:
                k, _, rest = ln.partition("=")
                values.setdefault(k, rest.partition("  #")[0].strip())
            for a in o.ask:
                values.setdefault(a.name, a.default)
                asks.append({"name": a.name, "label": a.label, "default": a.default, "type": a.type, "values": a.values})
        aj_env, seen = [], set()
        for e in context_env:
            item = dict(e)
            if item["name"] in values:
                item["default"] = values[item["name"]]
                item.pop("placeholder", None)
            seen.add(item["name"])
            aj_env.append(item)
        for k, v in values.items():
            if k not in seen:
                aj_env.append({"name": k, "default": v, "env_only": True})
        # What this combination runs, in words, before any YAML. Compose
        # references resolve the way compose would: the .env value, else the
        # ${VAR:-fallback}, else nothing.
        env_values: dict[str, str] = {}
        for ln in et.splitlines():
            k, sep, v = ln.partition("=")
            if sep and k.strip() and not k.lstrip().startswith("#"):
                env_values[k.strip()] = v.partition("  #")[0].strip()
        resolve = lambda text, ev=env_values: _re.sub(  # noqa: E731
            r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}",
            lambda m: ev.get(m.group(1)) or (m.group(2) or ""), text)
        parsed = (yaml.safe_load(ct) or {}).get("services") or {}
        parts, jails = [], []
        for sname, svc in parsed.items():
            img = resolve(str((svc or {}).get("image", "")))
            short = img.split("/")[-1]
            kind = "db" if sname in engine_services else "app"
            parts.append({"name": sname, "image": short, "kind": kind})
            jails.append({"name": sname.replace("-", "_") if kind == "app" else f"{cfg.image}_{sname}".replace("-", "_"), "image": short, "kind": kind})
        if any(o.id == "external" for o in opts):
            parts.append({"name": "your database", "image": "not run here", "kind": "none"})
            jails.append({"name": "your database", "image": "not run here", "kind": "none"})
        folders = []
        for svc in parsed.values():
            for v in (svc or {}).get("volumes") or []:
                if isinstance(v, str):
                    bits = v.split(":")
                    src, ro = resolve(bits[0]), len(bits) > 2 and "ro" in bits[2].split(",")
                else:
                    src, ro = resolve(str((v or {}).get("source", ""))), bool((v or {}).get("read_only"))
                if ro or not src.startswith("/") or src.startswith(("/etc/", "/dev/", "/var/run/", "/usr/")):
                    continue
                if src not in folders:
                    folders.append(src)
        for o in opts:
            for ln in o.env_lines:
                k, _, v = ln.partition("=")
                if k.endswith("_LOCATION") and v and v not in folders:
                    folders.append(v)
        folders = [f.replace("/containers", "@CONTAINER_CONFIG_ROOT@") for f in folders]
        director_text = director_env_text = ""
        if authored is not None:
            sliced = _director_for_option(authored, cfg, None if is_default else opts)
            director_text = _render_director_override(sliced)
            director_env_text = _render_override_env(sliced, {"name": cfg.image, "env": aj_env})
            jails = [{"name": str((svc or {}).get("name", n)), "image": next((p["image"] for p in parts if p["name"] == n), ""), "kind": "app"}
                     for n, svc in sliced["services"].items()]
        tpl = next((o for o in opts if o.jail_template_file), None)
        combos.append({
            "id": suffix or "default", "default": is_default,
            "selections": [{"choice": c.id, "choice_label": c.label, "option": o.id, "label": o.label, "default": o.id == c.default} for c, o in pairs],
            "label": ", ".join(o.label for _, o in pairs),
            "doc": " ".join(o.doc for _, o in pairs if o.doc),
            "parts": parts, "jails": jails, "folders": folders,
            "appjail": aj, "appjail_env": aj_env,
            "director_text": director_text, "director_env_text": director_env_text,
            "jail_template_file": tpl.jail_template_file if tpl else "", "jail_template": tpl.jail_template if tpl else "",
            "ask": asks,
            "compose_file": compose_file, "env_file": env_file,
            "compose_text": ct, "example_env": et,
            "compose_text_site": _site_placeholders(ct),
            "example_env_site": _site_placeholders(et, env_file=True),
            "zip": f"{cfg.image}-podman" + ("" if is_default else "-" + suffix.replace(".", "-")),
        })
    by_key = {tuple(sel["option"] for sel in cb["selections"]): cb for cb in combos}

    def tree(level: int, picked: tuple) -> dict | None:
        cs = cfg.metadata.choices
        if level >= len(cs):
            return None
        c = cs[level]
        nodes = []
        for o in sorted(c.options, key=lambda o: o.id != c.default):
            key = (*picked, o.id)
            nodes.append({"id": o.id, "label": o.label, "doc": o.doc, "default": o.id == c.default,
                          "children": tree(level + 1, key),
                          "combo": by_key.get(key) if level == len(cs) - 1 else None})
        return {"id": c.id, "label": c.label, "doc": c.doc, "options": nodes}

    declared = [{"id": c.id, "label": c.label, "doc": c.doc, "default": c.default,
                 "options": [{"id": o.id, "label": o.label, "doc": o.doc, "default": o.id == c.default} for o in c.options]}
                for c in cfg.metadata.choices]
    return {"choices": declared, "combos": combos, "tree": tree(0, ())}


def _enrich_metadata(cfg: Config, community_override: str | None = None) -> dict[str, Any]:
    """Build a context dict for templates with enriched env/vol/port data from Config."""
    meta = cfg.metadata
    docs = meta.docs if isinstance(meta.docs, dict) else {}

    # Extract jail allow.* parameters from annotations
    annotations = cfg.test.annotations if cfg.test else []
    jail_allow = [
        a.split("=")[0].replace("org.freebsd.jail.", "")
        for a in annotations
        if "org.freebsd.jail.allow." in a and "=true" in a.lower()
    ]
    mlock = "allow.mlock" in jail_allow
    sysvipc = "allow.sysvipc" in jail_allow

    # Check for AppJail support
    # meta.appjail is None = disabled, {} = bare/default, {...} = custom config
    appjail_meta = meta.appjail if hasattr(meta, "appjail") else None
    appjail_enabled = appjail_meta is not None or any(
        "io.daemonless.appjail" in a for a in annotations
    )

    # Check for Bastille OCI support (enabled by default; None = bastille: false)
    bastille_meta = meta.bastille if hasattr(meta, "bastille") else {}
    bastille_enabled = bastille_meta is not None

    # Community: Use CLI override, metadata if set (Format: Name:URL), or default to Daemonless Discord.
    community_name = ""
    community_url = ""
    community_raw = community_override or meta.community
    if not community_raw and "daemonless" in cfg.registry.lower():
        community_raw = DEFAULT_COMMUNITY

    if community_raw and ":" in community_raw:
        community_name, community_url = community_raw.split(":", 1)

    # Extract base version from Containerfile.j2 if present
    base_version = "15.1"  # fallback default
    cf_path = Path.cwd() / "Containerfile.j2"
    if cf_path.exists():
        match = re.search(r"ARG BASE_VERSION=(.*)", cf_path.read_text())
        if match:
            base_version = _normalize_base_version(match.group(1))

    context = {
        "name": cfg.image,
        "base_version": base_version,
        "title": meta.title,
        "description": meta.description,
        "category": meta.category,
        "upstream_url": meta.upstream_url,
        "web_url": meta.web_url,
        "freshports_url": meta.freshports_url,
        "user": meta.user,
        "jail_allow": jail_allow,
        "mlock": mlock,
        "sysvipc": sysvipc,
        "annotations": annotations,
        "upstream_binary": meta.upstream_binary,
        "icon": meta.icon,
        "logo": meta.logo,
        "logo_dark": meta.logo_dark,
        "healthcheck": meta.healthcheck,
        "notes": meta.notes,
        "readme": meta.readme,
        "community": community_raw,
        "community_name": community_name,
        "community_url": community_url,
        "registry": cfg.registry or "ghcr.io/daemonless",
        "repo_url": f"https://github.com/daemonless/{cfg.image}",
        "tags": [v.tag for v in cfg.variants] + [_doc_alias(a) for v in cfg.variants for a in (v.aliases or [])],
        "variants": [
            {
                "tag": v.tag,
                "aliases": [_doc_alias(a) for a in (v.aliases or [])],
                "default": v.default,
                "args": v.args or {},
                "containerfile": v.containerfile or "Containerfile",
                "tag_desc": v.tag_desc,
            }
            for v in cfg.variants
        ],
        "default_tag": next(
            (a for v in cfg.variants if v.default for a in ["latest"] if a in v.aliases),
            cfg.variants[0].tag if cfg.variants else "latest",
        ),
        "architectures": cfg.architectures,
        "appjail": appjail_meta,
        "appjail_enabled": appjail_enabled,
        "bastille": bastille_meta,
        "bastille_enabled": bastille_enabled,
        "docs": meta.docs,
        "deprecated": meta.deprecated,
        "screenshots": _collect_screenshots(Path.cwd()),
        "cit_mode": cfg.test.mode if cfg.test else "none",
        "image_class": meta.image_class,
        "compose_text": cfg.compose_text,
        "example_env": cfg.example_env,
        # The same, with the placeholders the site's settings panel fills in --
        # what a one-service page gets from its generated snippet.
        "compose_text_site": _site_placeholders(cfg.compose_text),
        "example_env_site": _site_placeholders(cfg.example_env, env_file=True),
        # What the compose offers (x-daemonless.choices): per option, the
        # flattened compose and .env a reader copies. Empty for most images.
        "choices": [],  # filled below, once env is known
        # The AppJail bundle carries the sidecar (x-daemonless.appjail.depends_on),
        # so its Director section runs the whole app, not the app alone.
        "appjail_sidecar": bool((getattr(meta, "appjail", None) or {}).get("depends_on")),
        "env": [],
        "volumes": [],
        "ports": [],
    }

    # Environment
    env_docs = {str(k): v for k, v in docs.get("env", {}).items()}

    # Ensure any explicitly documented env vars are included (critical for stacks)
    existing_env_names = {str(e["name"]) for e in cfg.env}
    for k, v in env_docs.items():
        if k not in existing_env_names:
            if isinstance(v, dict):
                cfg.env.append({"name": k, "default": str(v.get("default", ""))})
            else:
                cfg.env.append({"name": k, "default": ""})

    # An app shipped with its database reads its values from .env: show what
    # example.env gives, or the compose's own ${VAR:-fallback}, instead of the
    # raw reference (a Default column reading "${DB_PASSWORD}").
    env_file: dict[str, str] = {}
    for line in cfg.example_env.splitlines():
        k, sep, v = line.partition("=")
        if sep and k.strip() and not k.lstrip().startswith("#"):
            env_file[k.strip()] = v.strip()

    for e in cfg.env:
        name = e["name"]
        val = e["default"]

        if cfg.compose_text:
            ref = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}", str(val or ""))
            if ref:
                val = env_file.get(ref.group(1), ref.group(2) or "")
            elif not val:
                val = env_file.get(name, "")
        display_val = val if val and val not in ['""', "''"] else ""
        if not display_val and any(x in name.upper() for x in ["PASS", "KEY", "SECRET", "TOKEN"]):
            display_val = f"<{name.upper()}>"

        desc = env_docs.get(str(name), "")
        if isinstance(desc, dict):
            display_val = display_val or str(desc.get("default", ""))
            desc = desc.get("desc", "")

        item = {"name": name, "default": display_val, "desc": desc}
        if name in ["PUID", "PGID", "TZ"]:
            item["placeholder"] = f"@{name}@"
        context["env"].append(item)

    # Volumes
    vol_docs = {str(k): v for k, v in docs.get("volumes", {}).items()}
    for v in cfg.volumes:
        src = v["source"]
        tgt = v["target"]

        clean_target = tgt.strip("/").replace("/", "_").replace("-", "_").replace(".", "_").upper()
        vol_info = vol_docs.get(str(tgt), "")
        desc = vol_info.get("desc", "") if isinstance(vol_info, dict) else str(vol_info)
        optional = vol_info.get("optional", False) if isinstance(vol_info, dict) else False

        if tgt in SHARED_PATHS:
            source_path = tgt.lstrip("/")
            placeholder = f"@{clean_target}_PATH@"
            root_var = None
        elif tgt == "/config":
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_CONFIG_PATH@"
            source_path = cfg.image
            root_var = CONFIG_ROOT_VAR
        elif src == tgt:
            # Source equals target — host path is the literal mount point, not user-configurable
            source_path = src
            root_var = None
            placeholder = src
        elif src.startswith("./") or src.startswith("."):
            clean_src = src.lstrip("./")
            source_path = f"{cfg.image}/{clean_src}"
            root_var = CONFIG_ROOT_VAR
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_{clean_src.upper().replace('-', '_')}_PATH@"
        else:
            subdir = tgt.rstrip("/").split("/")[-1]
            if len(cfg.volumes) == 1 and subdir in ("config", "data"):
                source_path = cfg.image
            else:
                source_path = f"{cfg.image}/{subdir}"
            root_var = CONFIG_ROOT_VAR
            placeholder = f"@{cfg.image.upper().replace('-', '_')}_{subdir.upper().replace('-', '_')}_PATH@"

        context["volumes"].append({
            "path": tgt,
            "desc": desc,
            "optional": optional,
            "placeholder": placeholder,
            "source": source_path,
            "root_var": root_var,
            "options": v.get("options", "")
        })

    # Ports
    port_docs = {str(k): v for k, v in docs.get("ports", {}).items()}
    for p in cfg.ports:
        pub = p["published"]
        tgt = p["target"]
        proto = p["protocol"]

        context["ports"].append({
            "port": pub,
            "protocol": proto,
            "desc": port_docs.get(str(tgt), ""),
            "name": "web",
            "target": tgt
        })

    cc = _choice_context(cfg, context["env"])
    context["choices"], context["combos"], context["choice_tree"] = cc["choices"], cc["combos"], cc["tree"]
    # A stack whose author wrote the whole director: the README shows that,
    # not the one-service template, with the jail templates it ships.
    authored = _authored_director(cfg)
    context["director_override_text"] = _render_director_override(authored) if authored else ""
    context["director_override_env"] = _render_override_env(authored, context) if authored else ""
    context["sidecar_templates"] = _sidecar_templates(cfg)
    context["stack_parts"] = _stack_parts(cfg)
    return context


def is_appjail_enabled(cfg: Config) -> bool:
    """Whether this image opts into AppJail deployment.

    meta.appjail is None = disabled, {} = bare/default, {...} = custom; an
    ``io.daemonless.appjail`` annotation also enables it.
    """
    meta = cfg.metadata
    annotations = cfg.test.annotations if cfg.test else []
    appjail_meta = meta.appjail if hasattr(meta, "appjail") else None
    return appjail_meta is not None or any(
        "io.daemonless.appjail" in a for a in annotations
    )


def generate_appjail_files(
    cfg: Config,
    dest_dir: Path,
    *,
    image_ref: str | None = None,
) -> Path:
    """Render appjail-director.yml, .env, Makejail and template.conf into *dest_dir*.

    Per-file override: if ``.daemonless/appjail/<file>`` exists it is copied
    as-is; otherwise the bundled template is rendered.

    Parameters
    ----------
    cfg:
        Parsed build configuration.
    dest_dir:
        Directory to write files into (created if absent).
    image_ref:
        When set (test mode), the Makejail ``OPTION from=`` line points to
        this local image reference instead of the registry.
    """
    if jinja2 is None:
        raise ImportError("jinja2 is required for appjail file generation")

    dest_dir = Path(dest_dir)
    dest_dir.mkdir(parents=True, exist_ok=True)

    override_dir = Path.cwd() / ".daemonless" / "appjail"
    env = _get_jinja_env(Path.cwd())
    if env is None:
        raise RuntimeError("Could not find dbuild templates")

    context = _enrich_metadata(cfg)
    # "deploy" render: parameterize the published port and every volume device
    # through .env (WEB_PORT, one var per volume), so a consumer (fjord) injects
    # user values by writing .env alone and never edits director.yml. The docs
    # ("mkdocs") and hand-edit (default) renders are unaffected.
    context["render_mode"] = "deploy"
    if image_ref:
        context["image_ref"] = image_ref
    # Host networking is declared through the director options (ip4_inherit);
    # the jail template must carry the actual ip4/ip6 parameters because the
    # option itself is a no-op in AppJail 5.5.0.
    aj_opts = (cfg.metadata.appjail or {}).get("director", {}).get("options", []) if isinstance(cfg.metadata.appjail, dict) else []
    context["host_network"] = any(
        (isinstance(o, dict) and "ip4_inherit" in o) or (isinstance(o, str) and o.startswith("ip4_inherit"))
        for o in aj_opts
    )

    files = {
        "appjail-director.yml": "appjail-director.yml.j2",
        ".env":                 "appjail.env.j2",
        "Makejail":             "Makejail.j2",
        "template.conf":        "appjail-template.conf.j2",
    }

    # A full director override: an app (typically a multi-service stack) that
    # authored its complete `appjail.director` in x-daemonless. Emit that
    # verbatim instead of the single-service derivation, and build a .env
    # covering every ${VAR} it references.
    director_override = None
    aj_meta = cfg.metadata.appjail if isinstance(cfg.metadata.appjail, dict) else None
    if aj_meta:
        d = aj_meta.get("director")
        if isinstance(d, dict) and d.get("services"):
            # The bundle is the default answer to every choice: a jail behind
            # a profile (immich's public proxy) stays out, as its service does
            # under `podman-compose up` with no --profile.
            director_override = _director_for_option(d, cfg, None)

    # Every bundle file must end in exactly one newline. AppJail's Makejail
    # parser is line-based and silently DROPS a final line with no trailing
    # newline (an unterminated `OPTION from=...` yields a jail that is not an
    # OCI container, so `appjail oci set-user` fails). Jinja's default
    # keep_trailing_newline=False strips the template's own final newline, so
    # normalize on write instead of relying on the shared Environment.
    def _write_nl(path: Path, text: str) -> None:
        path.write_text(text.rstrip("\n") + "\n")

    for filename, template_name in files.items():
        override = override_dir / filename
        dest = dest_dir / filename
        if override.is_file():
            import shutil as _shutil
            _shutil.copy2(override, dest)
            log.info(f"AppJail: using override {override.relative_to(Path.cwd())}")
            continue
        if director_override is not None and filename == "appjail-director.yml":
            _write_nl(dest, _render_director_override(director_override))
            continue
        if director_override is not None and filename == ".env":
            _write_nl(dest, _render_override_env(director_override, context))
            continue
        try:
            tmpl = env.get_template(template_name)
            _write_nl(dest, tmpl.render(context))
        except jinja2.TemplateNotFound:
            log.warn(f"AppJail: template {template_name} not found, skipping")

    # A sidecar's own jail template (appjail.depends_on[].template, e.g. the
    # PostgreSQL sysvipc one) ships in the repo; it is part of the bundle, so
    # the consumer can drop the whole directory next to director.yml.
    for dep in (aj_meta or {}).get("depends_on", []) or []:
        tpl = dep.get("template") if isinstance(dep, dict) else None
        if not tpl:
            continue
        src = Path.cwd() / tpl
        if src.is_file():
            _write_nl(dest_dir / tpl, src.read_text())
        else:
            log.warn(f"AppJail: {dep.get('name')} references {tpl}, which is not in the repo")

    return dest_dir


def _render_director_override(director: dict) -> str:
    """Emit an author's complete `appjail.director` block as appjail-director.yml.

    PyYAML writes a bare null value as ``key: null``; AppJail's option/list form
    wants ``key:`` (bare), so those are normalized back.
    """
    import re as _re

    import yaml as _yaml
    body = _yaml.dump(director, sort_keys=False, default_flow_style=False)
    body = body.replace(": null\n", ":\n")
    # Authors write "!ENV '${VAR}'" as a string (YAML can't carry a tag inside
    # a plain mapping value the way the template does). PyYAML then emits it
    # quoted -- '!ENV ''${VAR}''' -- which director reads as literal text, not
    # a tag, and the jail gets the string "!ENV '${VAR}'" as its value.
    # Unquote so it is the tag pyaml-env resolves.
    # Text may come before the variable: "http://${HOST:127.0.0.1}:3003".
    body = _re.sub(r"""'!ENV ''([^']*\$\{[^}]+\}[^']*)'''""", r"!ENV '\1'", body)
    body = _re.sub(r'''"!ENV '([^']*\$\{[^}]+\}[^']*)'"''', r"!ENV '\1'", body)
    return "# appjail-director.yml\n\n" + body


def _render_override_env(director: dict, context: dict) -> str:
    """Build .env for a director override: DIRECTOR_PROJECT plus every ${VAR}
    the director references (PWD excluded -- the shell provides it), defaulting
    from the compose env where known."""
    import re as _re

    import yaml as _yaml
    text = _yaml.dump(director)
    seen, ordered = set(), []
    for name in _re.findall(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", text):
        if name != "PWD" and name not in seen:
            seen.add(name)
            ordered.append(name)
    defaults = {e["name"]: e.get("default", "") for e in context.get("env", [])}
    lines = ["# .env", "", f"DIRECTOR_PROJECT={context.get('name', '')}"]
    for name in ordered:
        lines.append(f"{name}={defaults.get(name, '')}")
    return "\n".join(lines) + "\n"


def _readme_generation_mode(cfg: Config, base: Path) -> str:
    """Decide how README.md generation should behave.

    Returns one of:

    - ``"generate"``: render README.md from the bundled/override template.
    - ``"manual-override"``: ``docs: manual`` but a local ``README.j2`` exists,
      so it is still rendered (just from the repo override).
    - ``"skip"``: ``docs: manual`` with no local ``README.j2`` — README.md is
      hand-maintained and must not be generated or drift-checked.
    """
    is_manual = (cfg.metadata.docs == "manual" or
                 (isinstance(cfg.metadata.docs, dict) and cfg.metadata.docs.get("manual", False)))
    has_local_readme_j2 = (base / "README.j2").exists()
    if is_manual and not has_local_readme_j2:
        return "skip"
    if is_manual and has_local_readme_j2:
        return "manual-override"
    return "generate"


def render_generated(
    cfg: Config,
    args: argparse.Namespace,
    base: Path | None = None,
) -> tuple[dict[str, str], list[str]]:
    """Render the artifacts ``dbuild generate`` would write, in memory.

    This is the shared rendering core used by both :func:`run` (which writes
    the files) and the ``dbuild lint --check-generated`` drift check (which
    compares them to disk). Keeping a single code path guarantees the check
    reflects exactly what generation produces.

    Returns ``(outputs, errors)`` where *outputs* maps each output filename to
    its full file content (header included, matching what would be written) and
    *errors* lists per-file render failures. Only files that generation would
    actually write are present in *outputs* (e.g. a ``docs: manual`` image with
    no ``README.j2`` yields no ``README.md`` entry).
    """
    base = base or Path.cwd()
    outputs: dict[str, str] = {}
    errors: list[str] = []

    if jinja2 is None:
        return outputs, ["jinja2 is not installed"]

    community_override = getattr(args, "community", None)
    context = _enrich_metadata(cfg, community_override)

    env = _get_jinja_env(base)
    if env is None:
        return outputs, ["could not find dbuild templates"]

    # README.md — uses the ChoiceLoader so the bundled template is a fallback.
    if _readme_generation_mode(cfg, base) != "skip":
        try:
            template = env.get_template("README.j2")
        except jinja2.TemplateNotFound:
            # Matches run(): warn + skip; README.md is left untouched.
            template = None
        if template is not None:
            try:
                outputs["README.md"] = template.render(context, render_mode="github")
            except jinja2.TemplateNotFound as e:
                # A TemplateNotFound here comes from an {% include %} inside
                # README.j2, not README.j2 itself, so name the real culprit.
                errors.append(
                    f"README.j2 failed to render: included template '{e.name}' not found"
                )

    # Stack choices render into the README (a section or a form per
    # combination, each with its zip on the site); nothing lands on disk for
    # them. Six generated files in a repo's root for two choices was clutter
    # nobody copied from.
    # Containerfiles — repo-only loader (local includes, no bundled fallback).
    for j2_path in sorted(base.glob("Containerfile*.j2")):
        out_name = j2_path.name.replace(".j2", "")
        try:
            repo_env = jinja2.Environment(loader=jinja2.FileSystemLoader(str(base)))
            template = repo_env.get_template(j2_path.name)
            outputs[out_name] = (
                HEADER_TEMPLATE.format(source=j2_path.name) + template.render(context)
            )
        except Exception as e:
            errors.append(f"Failed to render {out_name}: {e}")

    return outputs, errors


def run(cfg: Config, args: argparse.Namespace) -> int:
    """Generate documentation and Containerfiles."""
    if jinja2 is None:
        log.error("Jinja2 is not installed. Code generation requires it.")
        log.info("Run: pip install jinja2")
        return 1

    base = Path.cwd()

    if cfg.metadata.deprecated is not None:
        dep = cfg.metadata.deprecated
        msg = f"Image '{cfg.image}' is deprecated"
        if dep.replacement:
            msg += f" — suggested replacement: {dep.replacement}"
        log.warn(msg)

    env = _get_jinja_env(base)
    if not env:
        log.error("Could not find dbuild templates.")
        return 1

    readme_mode = _readme_generation_mode(cfg, base)
    if readme_mode == "skip":
        log.info("Skipping README.md generation (docs: manual)")
    elif readme_mode == "manual-override":
        log.info("docs: manual — using local README.j2 override")

    outputs, errors = render_generated(cfg, args, base)

    if (readme_mode != "skip" and "README.md" not in outputs
            and not any("README.j2" in e for e in errors)):
        log.warn("README.j2 template not found, skipping README.md")

    for name, content in outputs.items():
        (base / name).write_text(content)
        log.step(f"Generated {name}")
    for err in errors:
        log.error(err)

    return 0


# ── Drift check (generate --check) ────────────────────────────────────

def _is_image_repo(path: Path) -> bool:
    return (path / "compose.yaml").exists() or (path / ".daemonless" / "config.yaml").exists()


def check_repo(repo_path: Path) -> tuple[list[str], list[str]]:
    """Compare a repo's on-disk generated artifacts against a fresh render.

    Re-renders ``README.md`` and ``Containerfile*`` through the same code path
    as generation (:func:`render_generated`) and compares the result to what is
    committed on disk. This catches the common case of a ``.j2`` template being
    edited without re-running ``dbuild generate``.

    Returns ``(stale, notes)``:

    - *stale*: files that are missing or differ from a fresh render. Each
      message includes the fix (``run dbuild generate``).
    - *notes*: informational messages (e.g. README check skipped because the
      registry could not be resolved locally — see below).

    ``Containerfile*`` outputs use a literal ``FROM`` registry, so they are
    deterministic regardless of where the check runs. ``README.md`` embeds the
    registry derived from the git remote (or ``DBUILD_REGISTRY``); when neither
    is available the rendered registry would differ from the committed file, so
    the README comparison is skipped rather than reported as a false positive.
    """
    from dbuild import config as _config

    stale: list[str] = []
    notes: list[str] = []

    has_templates = (
        any(repo_path.glob("Containerfile*.j2"))
        or (repo_path / "README.j2").exists()
    )
    if not has_templates:
        return stale, notes

    cwd = Path.cwd()
    try:
        # _enrich_metadata reads Path.cwd() (base version, screenshots), so
        # render from inside the repo and always restore the original cwd.
        os.chdir(repo_path)
        cfg = _config.load(repo_path)
        args_ns = argparse.Namespace(community=None)
        outputs, render_errors = render_generated(cfg, args_ns, repo_path)

        stale.extend(render_errors)

        registry_confident = bool(
            os.environ.get("DBUILD_REGISTRY") or _config._git_remote_org()
        )

        for name, content in outputs.items():
            if name == "README.md" and not registry_confident:
                notes.append(
                    "README.md drift check skipped: registry unresolved"
                    " (no git remote / DBUILD_REGISTRY) — verify on CI/saturn"
                )
                continue
            dest = repo_path / name
            if not dest.exists():
                stale.append(f"{name} is missing — run dbuild generate")
            elif dest.read_text() != content:
                stale.append(f"{name} is out of date — run dbuild generate")
    except Exception as e:  # one bad repo must not abort the sweep
        stale.append(f"could not render generated files: {e}")
    finally:
        os.chdir(cwd)

    return stale, notes


def run_check(args: argparse.Namespace) -> int:
    """``dbuild generate --check``: fail if committed generated files are stale.

    Checks the current repo if run from an image directory, or every
    subdirectory if run from a workspace root (mirroring ``dbuild lint``).
    """
    cwd = Path.cwd()
    repos = [cwd] if _is_image_repo(cwd) else sorted(
        p for p in cwd.iterdir() if p.is_dir()
    )

    all_stale: dict[str, list[str]] = {}
    readme_skipped = 0
    for repo in repos:
        stale, notes = check_repo(repo)
        if stale:
            all_stale[repo.name] = stale
        if any("README" in n for n in notes):
            readme_skipped += 1

    if readme_skipped:
        log.info(
            f"README.md drift check skipped for {readme_skipped}"
            f" repo{'s' if readme_skipped != 1 else ''}"
            " (registry unresolved locally; verify on CI/saturn)."
        )

    if all_stale:
        print("\nOUT OF DATE:")
        print("=" * 60)
        for name, items in sorted(all_stale.items()):
            print(f"\n{name}:")
            for item in items:
                print(f"  - {item}")
        n = len(all_stale)
        print(
            f"\n{n} repo{'s' if n != 1 else ''} out of date"
            " — run 'dbuild generate' to update"
        )
        return 1

    print("All generated files are up to date")
    return 0
