name: {{ name }}

x-daemonless:
  title: "{{ title }}"
  icon: ":material-apps:"  # https://pictogrammers.com/library/mdi/ (material-) or https://simpleicons.org/ (simple-)
  category: "{{ category }}"
  description: "{{ description }}"
  upstream_url: "{{ upstream_url }}"
  web_url: "{{ web_url }}"
  freshports_url: "{{ freshports_url }}"
  user: "bsd"
  mlock: {{ mlock_bool }}
  community: "{{ community }}"
  appjail: true

  docs:
    env:
      PUID: "User ID for the application process"
      PGID: "Group ID for the application process"
      TZ: "Timezone for the container"
    volumes:
      /config: "Configuration directory"
    ports:
      {{ port }}: "Web UI"

services:
  {{ name }}:
    image: ghcr.io/daemonless/{{ name }}:latest
    container_name: {{ name }}
    restart: unless-stopped
{%- if mlock %}

    annotations:
      org.freebsd.jail.allow.mlock: "true"
{%- endif %}

    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC

    volumes:
      - /path/to/containers/{{ name }}:/config

    ports:
      - {{ port }}:{{ port }}
